prompt_dirs: # relative to the location of this file
  - "./datatalk/agent/kraken/prompts"
  - "./kraken/prompts"

litellm_set_verbose: false

prompt_logging:
  log_file: "./prompt_logs.jsonl"
  prompts_to_skip:
    - "if_remove_datapoint.prompt"
    - "modify_datapoint.prompt"

llm_endpoints:
  - api_base: https://api.openai.com/v1
    api_key: OPENAI_API_KEY
    engine_map:
      gpt-4o: gpt-4o-2024-11-20
      gpt-4o-mini: gpt-4o-mini-2024-07-18